travis:
  secure:
    BINSTAR_TOKEN: HnkG6Bcf46d02I1SwBMqrCqeDErbFVCaBj7XGLXQPiUL1up80jb+jkXAwsTm8U9DG3CuO1MnptMUrYe0zRoqSh2WB/C3UyqgZajPbajjf70e3yVgm4t0lXsRV/sH6BPo39sU6obdYIDzdVlRcF4QvNcmovYWPAAdQ/Rx3/ioXoX7Tuy76u5bM3NH153xihjftn+F+9KNOeIkQCsLdF6AVahMQZKD+zc+WvZRoZDx/bpaod8mGejwOz58YWWRPmdZRkRigEBRyBTNJ+roT7qFr07JAF21kBujdVH725/a3P6AzEYCsQB70yO4ElDYrunZ1IqLIRDEl42/9hwaxkI3FInMYvsE/XFX/AcA6YuXNVbacn8Q433is6l2VNg9SDX12eLBMDApBgO+7u0TPzGYrT4Lug75uE6inrZSpE872Bg3bXGIR0rbDLphpbWegAKLRSCoMDwtiS9x5miAgckMgE+0JDVZj6QnttITnb/D/vFFFgCASBG7tGsrI4fHsabfW+wlOYIQ87WElr+T8gGpUexmscZjj9qyDhjwRLqrsUw6eUn5OwgM0HAr91ev2lOnDDaBiIwgNqY0QJ/D88PCE6k9oyab5Dwc5ljWHkg3eiUCjR/xsnnFW82Zm44SqyEcmcizP8EC1Ete6PuQ39IzhhhpVh2xpwhBs1n4WAeE2NQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
